//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangThietBiDienTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietNhapHang
    {
        public int MaNhap { get; set; }
        public int MaSP { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> DonGia { get; set; }
    
        public virtual NhapHang NhapHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
