//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangThietBiDienTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GioHang
    {
        public GioHang()
        {
            this.ChiTietGioHangs = new HashSet<ChiTietGioHang>();
        }
    
        public int MaGioHang { get; set; }
        public int MaKH { get; set; }
        public System.DateTime NgayTao { get; set; }
    
        public virtual ICollection<ChiTietGioHang> ChiTietGioHangs { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
