//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangThietBiDienTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HINHANH
    {
        public int MaAnh { get; set; }
        public Nullable<int> MaSP { get; set; }
        public string TenAnh { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
