//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangThietBiDienTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhapHang
    {
        public NhapHang()
        {
            this.ChiTietNhapHangs = new HashSet<ChiTietNhapHang>();
        }
    
        public int MaNhap { get; set; }
        public int MaNCC { get; set; }
        public int MaNV { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public Nullable<decimal> TongTien { get; set; }
    
        public virtual ICollection<ChiTietNhapHang> ChiTietNhapHangs { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
    }
}
