//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuaHangThietBiDienTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        public int MaTaiKhoan { get; set; }
        public int MaNguoiDung { get; set; }
        public string Email { get; set; }
        public string MatKhau { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
